/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab8P2_CarmenCastillo;

/**
 *
 * @author casti
 */
public class MainLab8 extends javax.swing.JFrame {

    /**
     * Creates new form MainLab8
     */
    public MainLab8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userLabel3 = new javax.swing.JLabel();
        txtf_UsuarioIS = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        userLabel4 = new javax.swing.JLabel();
        txtf_ContraIS = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_IS = new javax.swing.JButton();
        userLabel5 = new javax.swing.JLabel();
        btn_CrearCuenta = new javax.swing.JButton();
        btn_MainMod = new javax.swing.JButton();
        userLabel22 = new javax.swing.JLabel();
        btn_ISAdmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("INICIO DE SESIÓN");

        userLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        userLabel3.setForeground(new java.awt.Color(51, 51, 51));
        userLabel3.setText("USUARIO");

        txtf_UsuarioIS.setBackground(new java.awt.Color(204, 204, 204));
        txtf_UsuarioIS.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtf_UsuarioIS.setBorder(null);

        userLabel4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        userLabel4.setForeground(new java.awt.Color(51, 51, 51));
        userLabel4.setText("Contraseña");

        txtf_ContraIS.setBackground(new java.awt.Color(204, 204, 204));
        txtf_ContraIS.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtf_ContraIS.setBorder(null);

        btn_IS.setBackground(new java.awt.Color(0, 0, 0));
        btn_IS.setForeground(new java.awt.Color(255, 255, 255));
        btn_IS.setText("INGRESAR");
        btn_IS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ISMouseClicked(evt);
            }
        });

        userLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        userLabel5.setForeground(new java.awt.Color(51, 51, 51));
        userLabel5.setText("/");

        btn_CrearCuenta.setBackground(new java.awt.Color(0, 0, 0));
        btn_CrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btn_CrearCuenta.setText("CREAR CUENTA");
        btn_CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CrearCuentaMouseClicked(evt);
            }
        });

        btn_MainMod.setBackground(new java.awt.Color(0, 0, 0));
        btn_MainMod.setForeground(new java.awt.Color(255, 255, 255));
        btn_MainMod.setText("MODIFICAR CUENTAS");
        btn_MainMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MainModMouseClicked(evt);
            }
        });

        userLabel22.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        userLabel22.setForeground(new java.awt.Color(51, 51, 51));
        userLabel22.setText("/");

        btn_ISAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btn_ISAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btn_ISAdmin.setText("INGRESAR COMO ADMINISTRADOR");
        btn_ISAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ISAdminMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("O");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userLabel4)
                                .addComponent(txtf_ContraIS)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userLabel3)
                                .addComponent(txtf_UsuarioIS)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_IS, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userLabel5)
                                    .addComponent(userLabel22))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_MainMod)
                            .addComponent(btn_ISAdmin))))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(userLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_UsuarioIS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(userLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_ContraIS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_IS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel22)
                    .addComponent(btn_ISAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel5)
                    .addComponent(btn_MainMod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ISMouseClicked

        boolean correct = false;
        for (int i = 0; i < jugadores.size(); i++) {
            if (jugadores.get(i).getContra().equals(txtf_ContraIS) && jugadores.get(i).getUser().equals(txtf_UsuarioIS.getText())) {
                //vMenuPrincipal.setVisible(true);
                this.setVisible(false);
                correct = true;
            }
        }

        if (!correct) {
            JOptionPane.showMessageDialog(null, "Usuario y/o Contraseña incorrectos.");
            txtf_ContraIS.setText("");
            txtf_UsuarioIS.setText("");
        }

    }//GEN-LAST:event_btn_ISMouseClicked

    private void btn_CrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearCuentaMouseClicked

        vCrearCuenta.pack();
        vCrearCuenta.setLocationRelativeTo(null);
        vCrearCuenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CrearCuentaMouseClicked

    private void btn_MainModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MainModMouseClicked
        vModificarJugador.pack();
        vModificarJugador.setLocationRelativeTo(null);
        vModificarJugador.setVisible(true);
        llenarcomboModCarro();
        this.setVisible(false);
    }//GEN-LAST:event_btn_MainModMouseClicked

    private void btn_ISAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ISAdminMouseClicked

        if (txtf_UsuarioIS.getText().equals("ADMIN") && txtf_ContraIS.getText().equals("ADMIN")) {

            this.setVisible(false);
            vAdministrador.pack();
            vAdministrador.setLocationRelativeTo(null);
            vAdministrador.setVisible(true);

            //llenarcbTipoList();
        } else {

            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña equivocados / Su usuario no es Administrador.");

        }
    }//GEN-LAST:event_btn_ISAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLab8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrearCuenta;
    private javax.swing.JButton btn_IS;
    private javax.swing.JButton btn_ISAdmin;
    private javax.swing.JButton btn_MainMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtf_ContraIS;
    private javax.swing.JTextField txtf_UsuarioIS;
    private javax.swing.JLabel userLabel22;
    private javax.swing.JLabel userLabel3;
    private javax.swing.JLabel userLabel4;
    private javax.swing.JLabel userLabel5;
    // End of variables declaration//GEN-END:variables
}
